create table if not exists public.organizations (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.org_buildings (
  id bigint generated by default as identity primary key,
  organization_id bigint references public.organizations(id) on delete cascade,
  "buildingName" text not null,
  "buildingAbre" text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.stations (
  id bigint generated by default as identity primary key,
  lat double precision not null,
  lng double precision not null,
  organization_id bigint references public.organizations(id) on delete set null,
  "buildingAbre" text,
  "buildingName" text,
  "buildingDetails" text,
  "filterStatus" text not null default 'GREEN',
  "stationStatus" text not null default 'GREEN',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tickets (
  id bigint generated by default as identity primary key,
  user_id bigint,
  author_profile_key text,
  author_username text,
  author_avatar_emoji text,
  station_id bigint not null references public.stations(id) on delete cascade,
  title text not null,
  body text,
  status text not null default 'OPEN',
  category text not null default 'OTHER',
  priority text not null default 'MEDIUM',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_org_buildings_org_id on public.org_buildings(organization_id);
create index if not exists idx_org_buildings_name on public.org_buildings("buildingName");
create index if not exists idx_org_buildings_abre on public.org_buildings("buildingAbre");
create index if not exists idx_stations_org_id on public.stations(organization_id);
create index if not exists idx_tickets_station_id on public.tickets(station_id);
create index if not exists idx_tickets_author_profile_key on public.tickets(author_profile_key);
